version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  ui-build:

services:

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/api/storage:/usr/share/nginx/storage
      - ui-build:/usr/share/nginx/html
    restart: always
    networks:
      - app_network

  api:
    container_name: api
    hostname: api
    build:
      context: ./app/api
      args:
        - NPM_REGISTRY=${NPM_REGISTRY:-https://registry.npmjs.org/}
        - BUILD_ENV=${BUILD_ENV:-production}
        - ${API_PORT:-3000}:${API_PORT:-3000}
    expose:
      - ${API_PORT:-3000}
    volumes:
      - ./app/api/config:/app/config
      - ./app/api/src:/app/src
      - ./app/api/storage:/app/storage
    restart: always
    networks:
      - app_network
    env_file:
      - ${ENV_FILE:-./.env}
    environment:
      - BUILD_ENV=${BUILD_ENV:-production}
    depends_on:
      - nginx
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

  ui:
    container_name: ui
    build:
      context: ./app/ui
      args:
        - NPM_REGISTRY=${NPM_REGISTRY:-https://registry.npmjs.org/}
    volumes:
      - ui-build:/app/build
    networks:
      - app_network
    depends_on:
      - nginx
